### DISCUSSION TITLE
How can I dynamically map MQTT topics to ROS topics without predefined IDs?

### DISCUSSION THREAD

**Discussion by manudelu** [ika-rwth-aachen/mqtt_client#73] [Q&A]
In my project I need to map telemetry data from multiple MQTT topics to corresponding ROS topics. Each drone publishes its data to a unique MQTT topic (e.g., fleet/drone1/telemetry, fleet/drone2/telemetry , etc.). My goal is to bridge these MQTT topics to corresponding ROS topics (e.g., /drone1/telemetry, /drone2/telemetry) without knowing the number of drones in advance.

Config file:

```
 broker:
  host: localhost
  port: 1883
bridge:
  mqtt2ros:
    - mqtt_topic: fleet/drone1/telemetry
      ros_topic: /drone1/telemetry_data
      primitive: false  
```

Do I need to manually specify every single topic or is it possible to use wildcards (+) to dynamically subscribe to topics like fleet/+/telemetry ?
