### ISSUE TITLE
Saw-tooth latencies due to poll system call in paho.mqtt.c v1.3.10

### ISSUE THREAD

**Issue by lreiher** [ika-rwth-aachen/mqtt_client#2]
## Problem Description

Latencies measured with the built-in latency measurement feature continuously grow up to about 0.1s, then drop down again.

![image](https://user-images.githubusercontent.com/46258835/182840788-0a983a8d-dfc2-4249-99a7-9eba86e34e8e.png)

## Troubleshooting

The problem started to occur when upgrading [paho.mqtt.c](https://github.com/eclipse/paho.mqtt.c) from v1.3.9 to v1.3.10. It has been tested that the issue is due to the 

[From the release notes of v1.3.10:](https://github.com/eclipse/paho.mqtt.c/releases/tag/v1.3.10)
 > A significant internal change is to use the poll system call instead of select to monitor sockets. Most people should notice no difference, except that poll does not exist on Windows XP as select does. You can use the USE_SELECT compile definition to switch back to use select for those platforms that don't have poll.

It has been tested that the issue is indeed gone when building paho.mqtt.c manually with `-DPAHO_USE_SELECT=ON`.

The version of paho.mqtt.c that is released as ROS package [paho-mqtt-c](https://github.com/nobleo/paho.mqtt.c-release) has this flag set to its default value `OFF`, as can be [verified here](https://github.com/nobleo/paho.mqtt.c-release/blob/release/noetic/paho-mqtt-c/CMakeLists.txt#L55).

## Steps to reproduce

1. Launch the Mosquitto MQTT broker
    ```
   docker run --rm --network host --name mosquitto eclipse-mosquitto
    ```
1. Install `mqtt_client`
    ```
    sudo apt install ros-noetic-mqtt-client
    source /opt/ros/noetic/setup.bash
    ```
1. Create a new `params.yaml` with the following contents
    ```yml
    broker:
      host: localhost
      port: 1883
    bridge:
      ros2mqtt:
        - ros_topic: /ping
          mqtt_topic: pingpong
          inject_timestamp: true
      mqtt2ros:
        - mqtt_topic: pingpong
          ros_topic: /pong
    ```
1. Launch `mqtt_client` with the parameters
    ```
    roslaunch mqtt_client standalone.launch params_file:=$(pwd)/params.yaml
    ```
1. Publish a ROS message at 100Hz to the subscribed `/ping` topic
    ```
    rostopic pub -r 100 /ping std_msgs/String "Hello MQTT"
    ```
1. Plot the measured latencies for the round-trip from `/ping` to `/pong`
    ```
    rqt_plot /mqtt_client/latencies/pong
    ```
